name: loyalty_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.12
  dropdown_textfield: ^1.2.0
  feedback: ^3.1.0
  carousel_slider: ^5.0.0
  get: ^4.7.2
  lottie: ^3.2.0
  keyboard_avoider: ^0.2.0
  font_awesome_flutter: ^10.5.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.2.1  
  universal_html: ^2.0.8 
  mobile_scanner: ^7.0.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.10
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  googleapis_auth: ^2.0.0
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.4.2
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # flutter_launcher_name: ^0.0.2

# ✅ App Icon Config
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png" # <-- apna logo ka path

# ✅ App Name Config
flutter_launcher_name:
  name: "Angelopoulos Hair"

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/icons/
    - assets/fonts/jura/Jura-Regular.ttf
    - assets/fonts/jura/Jura-Bold.ttf
    - assets/fonts/jura/Jura-Medium.ttf
    - assets/fonts/poppins/Poppins-Regular.ttf
    - assets/fonts/poppins/Poppins-Bold.ttf
    - assets/fonts/poppins/Poppins-Medium.ttf
    - assets/fonts/Noto_Sans/NotoSans-Regular.ttf
    - assets/fonts/Noto_Sans/NotoSans-Bold.ttf
    - assets/service_account.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
    - family: Jura
      fonts:
        - asset: assets/fonts/jura/Jura-Regular.ttf
        - asset: assets/fonts/jura/Jura-Bold.ttf
          weight: 700
        - asset: assets/fonts/jura/Jura-Medium.ttf
          weight: 500
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Bold.ttf
          weight: 700

  # ✅ Enable localization generation
  generate: true

# ✅ Root level localization config
flutter_gen:
  l10n:
    enabled: true
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
